/* 
**  mod_load_monitor.c -- Apache sample load_monitor module
**  [Autogenerated via ``apxs -n load_monitor -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_load_monitor.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /load_monitor in as follows:
**
**    #   httpd.conf
**    LoadModule load_monitor_module modules/mod_load_monitor.so
**    LoadMonitor 10 "ps auwx >> /tmp/ps.log"
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /load_monitor and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/load_monitor 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_load_monitor.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "http_log.h"
#include "http_request.h"
#include "apr_strings.h"
#include "ap_config.h"
#include <stdlib.h>

#define MODULE_NAME           "mod_load_monitor"
#define MODULE_VERSION        "0.0.1"

module AP_MODULE_DECLARE_DATA load_monitor_module;

typedef struct _lm_dir_conf_t {

    double load;
    char *cmd;

} lm_dir_conf_t;

static void *lm_create_dir_config(apr_pool_t *p, char *dir)
{
    lm_dir_conf_t *dconf = (lm_dir_conf_t *)apr_pcalloc(p, sizeof(lm_dir_conf_t));

    dconf->load = 0;
    dconf->cmd  = NULL;

    return dconf;
}

static const char *set_load_monitor_cmd(cmd_parms *cmd, void *dconf_fmt, char *la, char *lmcmd)
{
    double set_la = atof(la);

    if (set_la < 0)
        return "invalid Load";

    lm_dir_conf_t *dconf = (lm_dir_conf_t *)dconf_fmt;
    dconf->load = set_la;
    dconf->cmd  = apr_pstrdup(cmd->pool, lmcmd);

    return NULL;
}

static int load_monitor_init(apr_pool_t *p, apr_pool_t *plog, apr_pool_t *ptemp, server_rec *server)
{

    ap_log_error(APLOG_MARK
        , APLOG_INFO
        , 0
        , NULL
        , "%s %s: %s / %s mechanism enabled."
        , MODULE_NAME
        , __func__
        , MODULE_NAME
        , MODULE_VERSION
    );

    return OK;
}

static int load_monitor_access_checker(request_rec *r)
{
    lm_dir_conf_t *dconf = ap_get_module_config(r->per_dir_config, &load_monitor_module);
    int status;
    double cload[3];

    cload[0] = cload[1] = cload[2] = -1;
    getloadavg(cload, 3);

    if (cload[1] == -1)
        return HTTP_SERVICE_UNAVAILABLE;

    if (dconf->load < cload[1]) {
        status = system(dconf->cmd);
        ap_log_perror(APLOG_MARK
            , APLOG_DEBUG
            , 0
            , r->pool
            , "%s DEBUG %s: cmd: %s code: %d (current load: %f threshold load: %f)"
            , MODULE_NAME
            , __func__
            , dconf->cmd
            , status
            , cload[0]
            , dconf->load
        );
    }
    return DECLINED;
}

static const command_rec load_monitor_cmds[] = {
    AP_INIT_TAKE2("LoadMonitor", (void *)set_load_monitor_cmd, NULL, RSRC_CONF | ACCESS_CONF | OR_LIMIT, "Set command over Load Average."),
    {NULL}
};

static void load_monitor_register_hooks(apr_pool_t *p)
{
    ap_hook_post_config(load_monitor_init, NULL, NULL, APR_HOOK_MIDDLE);
    ap_hook_access_checker(load_monitor_access_checker, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA load_monitor_module = {
    STANDARD20_MODULE_STUFF, 
    lm_create_dir_config,                   /* create per-dir    config structures */
    NULL,                                   /* merge  per-dir    config structures */
    NULL,                                   /* create per-server config structures */
    NULL,                                   /* merge  per-server config structures */
    load_monitor_cmds,                      /* table of config file commands       */
    load_monitor_register_hooks             /* register hooks                      */
};

